<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::create([
            'name'=>'p1',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-1.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p2',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-2.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p3',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-3.png',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p4',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-4.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p5',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-5.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p6',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-6.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p7',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-7.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p8',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-8.png',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p9',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-9.png',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p10',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-10.png',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p11',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-11.png',
            'user_id'=>1,
            'stock'=>4,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p12',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-12.png',
            'user_id'=>1,
            'stock'=>5,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p13',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-13.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p14',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-14.jpg',
            'user_id'=>1,
            'stock'=>10,
            'category_id'=>'1',
        ]);
        Product::create([
            'name'=>'p15',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-15.jpg',
            'user_id'=>1,
            'stock'=>3,
            'category_id'=>'1',
        ]);
        
        Product::create([
            'name'=>'p17',
            'desc'=>'loremlkdjlkdjflkvdfvlkdfvk',
            'price'=>50,
            'img'=>'img-17.jpg',
            'user_id'=>1,
            'stock'=>4,
            'category_id'=>'1',
        ]);
    }
}
